coreProjectLocation:
  prd:
    prdFile: docs/prd.md
    prdVersion: v3      # switch to v4 after migration
    prdSharded: false
  architecture:
    architectureFile: docs/architecture.md
    architectureVersion: v3
    architectureSharded: false
  devLoadAlwaysFiles:
    - docs/bmad-journal.md
